apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/lucasshawn/billable.git
    targetRevision: HEAD
    path: /src/helm/test
  destination:
    server: https://kubernetes.default.svc
    namespace: test